### ISSUE TITLE
Possibility to choose the preferred mask

### ISSUE THREAD

**Issue by renatomefidf** [eXistenZNL/PermCheck#5]
It would be nice if I could be able to choose the mask I want to have:
```xml
<permcheck>
    <mask value="750">
        <pattern>./src/*.php</pattern>
    </mask>
    <mask value="775">
        <pattern>./tmp/*.log</pattern>
    </mask>
    <excludes>
        <dir>.git</dir>
        <dir>vendor/</dir>
        <dir>dev/</dir>
    </excludes>
    <executables>
        <file>bin/console</file>
        <file>bin/symfony_requirements</file>
    </executables>
</permcheck>
```

The structure can be different, of course, this is just the concept!

**Comment by eXistenZNL** [comment]
Good idea, but the thing is that git only understands "executable" or not and has no idea of masks. If a file has the user part set to executable (u+x) it is shown in git as 100775, and if the user part is not set to executable, it is shown as 100664.

The bits g+x or o+x are completely ignored by git, so, there is no need for masks since it wouldn't be picked up anyway :)

You can easily test this out by yourself by setting o+x on a file and then checking git diff :+1:

**Comment by renatomefidf** [comment]
Amazing! I didn't now that:
```
diff --git a/build.xml b/build.xml
old mode 100644
new mode 100755
```
